@startuml
skinparam monochrome false
skinparam packageStyle rectangle
skinparam shadowing true

skinparam classAttributeIconSize 0

hide circle
hide methods

title Domain Model

class SystemAdministrator{
    emailAddress
    password
}


class networkManager {
assignedAgencies
}

class storeManager {
agency
}

class Property{
    area
    distanceFromCenter
    price
}

class Agent{
    name
    citizenCardNumber
    taxNumber
    address
    emailAddress
    telephoneNumber
}

class Agency{
    designation
    phoneNumber
    emailAddress
}

class Buyer{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class Owner{
    name
    citizenCardNumber
    taxNumber
    address
    email
    telephoneNumber
}

class UnregisteredUser{
    designation
}

class Announcement{
    typeOfBusiness
    typeOfProperty
    area
    location
    distanceFromCenter
    price
    photos
}

class TypeOfBusiness {
designation
}

class Land {
designation
}

class Habitation {
    numberOfBedrooms
    numberOfBathrooms
    numberOfParkingSpaces
    availableEquipment
}

class Location {
    street
    district
    zipcode
    city
    state
}

class Apartment{
    designation
}

class House {
    basement
    inhabitableLoft
    sunExposure
}

class AnnouncementType{
    designation
}

class Sale{
    requestedPrice
}

class Lease{
    requestedFee
    duration
}

class Commission{
    typeOfCommission
    value
}

SystemAdministrator "1" ---> "*" Agent : creates
SystemAdministrator "1" ---> "*" Agency : creates

Buyer "*" ---> "*" Agent : contacts for purchase
Buyer "*" ---> "*" Announcement : views

Owner "*" ---> "*" Agent : contacts for sale/rent
Owner "*" ---> "*" Property : owns

UnregisteredUser "*" ---> "*" Announcement : views

Property "1.." -left-> "1" UnregisteredUser: is displayed by
Property "1" -left-> "1" TypeOfBusiness: is categorized by
Property "1" -left-> "*" Announcement : has
Property "1" -right-> "*" Land: can be
Property "1" -down-> "1" Location: has
Property "1" -right-> "*" Habitation : can be

Habitation "1" --> "0.." House : can be
Habitation "1" --> "0.." Apartment: can be

Agency "1" --> "1" Employee : has multiple
Employee "1" --> "0" storeManager : can be
Employee "1" --> "0" networkManager : can be
Employee "1" --> "0" Agent : can be


Agent "1" --> "1" Roles : has one
Agent "*" ---> "*" Announcement : publishes
Agent "1" -- "1" Commission : defines a

Announcement "1" -- "0.." AnnouncementType: has
AnnouncementType "1" -- "0.." Sale: can be
AnnouncementType "1" -- "0.." Lease: can be


@enduml